name: Linkspector code
on: [push]
jobs:
  check-links:
    name: Check linkspector code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run linkspector code
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          fail_on_error: true
          fail_level: error
          filter_mode: nofilter
          config_file: .linkspector.yml
