name: Linkspector wiki
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # Optional: allows manual triggering

jobs:
  check-links:
    name: Check linkspector wiki
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
      - name: Run linkspector wiki
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          fail_on_error: true
          fail_level: error
