name: Markdown linter

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: Linting all markdown files
    runs-on: ubuntu-latest

    steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: articulate/actions-markdownlint@v2
        with:
          config: markdownlint-config.json
          files: '**/*.md'
