name: Update KP igÃ©ny json

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.14
      uses: actions/setup-python@v4
      with:
        python-version: '3.14.2'

    - name: Execute process_kp_igeny.py
      run: python code/process_kp_igeny.py

    - name: Check for Changes
      run: |
        if [[ $(git status --porcelain) ]]; then
          echo "files_modified=true" > $GITHUB_ENV
        else
          echo "files_modified=false" > $GITHUB_ENV
        fi

    - name: Configure Git
      if: ${{ env.files_modified == 'true' }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit Changes
      if: ${{ env.files_modified == 'true' }}
      run: |
        git add .
        git commit -m "GitHub Action: data/tables/kepzettseg_kp.json"

    - name: Push Changes
      if: ${{ env.files_modified == 'true' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push
